# Generated by tools/generate_ic_elk_deps.py
IC_RUNTIME_DEPS = [
    ":basedpyright",
    ":hypothesis",
    ":llm-tldr",
    ":mcp",
    ":networkx",
    ":pydantic",
    ":pytest",
    ":pytest-snapshot",
    ":ruff",
    ":rx",
]
